### ISSUE TITLE
Browser support roadmap

### ISSUE THREAD

**Issue by jmatsushita** [awslabs/mls-rs#77]
Currently tests:
- ✅  pass on Chrome 
- 🚫  fail in Firefox `122.0.1 (64-bit)`
- 🚫  fail in Safari `Version 17.1.2 (19616.2.9.11.12)`

<details><summary>Sample test error output in Firefox</summary>
failures:

---- mls_rs::tree_kem::private::tests::test_update_leaf output ----
    error output:
        panicked at mls-rs/src/tree_kem/private.rs:128:14:
        called `Result::unwrap()` on an `Err` value: HpkeError(AnyError(KemError(AnyError(KeyDerivationError))))
       
</details>

Could you please provide information about your intentions with regards to browser support? 

Also do you intend to submit `mls-rs` to https://github.com/mlswg/mls-implementations ?

Thank for the library!

Cheers,

Jun

**Comment by tomleavy** [comment]
Hey Jun,

The problem we have run into is that one of the key derivation functions that MLS requires does not work in the current standard for the WebCrypto module that ships with browsers. We got chrome to work by using a hack that seems to not work on Firefox or Safari. The best path to success would be to build WASM with the RustCrypto based crypto to avoid problems with browser compatibility. 

We also don't have any wasm bindgen in our codebase, so in the current state it would be difficult to import into a web project. Our focus has moved towards helping browsers natively adopt MLS in the same way they support webrtc and other technologies, but in the meantime feel free to contribute anything you think helps!
